### PR TITLE
Fixes #1236 Fixed version number for metacpan search

### LINKED ISSUE #1236: Failing to download a CPAN module
FPM Fails to download Rex-Repositorio CPAN module when converting.  Will investigate.

### PR DESCRIPTION
**Pull request by liger1978**
The new way of searching metacpan with an http `POST` consistently requires numerical version number (i.e. no `v` prefix).  This patch tested against 73 CPAN modules: https://gitlab.com/harbottle/epmel/builds/6722395

### CODE REVIEW

**Comment by liger1978** [comment]
It's only the OSX build failing travis-ci (as usual)...

File: lib/fpm/package/cpan.rb [hunk 1]
```diff
@@ -309,17 +309,16 @@ def download(metadata, cpan_version=nil)
                  :distribution => distribution,
                  :version => cpan_version)
 
-    # default to latest versionunless we specify one
+    # default to latest version unless we specify one
     if cpan_version.nil?
-      self.version = metadata["version"]
+      self.version = "#{metadata["version"]}"
```
Comment (jordansissel) [inline lib/fpm/package/cpan.rb]: this can just be `self.version = metadata["version"]` I think.

**Comment by jordansissel** [comment]
Lovely thank you! I made one comment for a style change, but it's minor and I am happy to merge.

**Comment by jordansissel** [comment]
@liger1978 how would you characterize this change, a bug fix? new feature?

File: lib/fpm/package/cpan.rb (hunk 1 above)
Comment (liger1978) [inline lib/fpm/package/cpan.rb]: It was just belt and braces to ensure self.version was a string before attempting the substitution below.

**Comment by liger1978** [comment]
@jordansissel A bug

File: lib/fpm/package/cpan.rb (hunk 1 above)
Comment (jordansissel) [inline lib/fpm/package/cpan.rb]: Gotcha. My preferred way to do this is to call `.to_s` on the object: `metadata["version"].to_s`

No change required. Thanks for the explanation :)

**Comment by jordansissel** [comment]
@liger1978 ok cool, noted for the release notes <3
